--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels: 
    name: grafana_persistent
  name: grafanapvc
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests: 
      storage: 1Gi
