apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: prometheuspvc
  labels: 
     name: prometheus_persistent

spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi